# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a3ae7a120da85c287feb5e27a6171ba21cb8d675fb9e42eac05b54aae4a0278873c800f43a71cce383c880d15bbf12fceeef6bc872d3386624e38039c7e1a5

test:
  secret_key_base: c0a37efa5b114433f0494b48ff182c47b9231f7dae0ff0d65381aafc3a0d44a4befea8acc1518d9e7931e507c0e405f44efa35125850369b3c5b6293ce47c1f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
