# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c6937ddd9b6751558448f359b18a97c6a54f12d8aae4cf844fbdebe334f68d4af8f08f6dc679203c02d8a4e05e477d5c11222a216dec02ad999e2b075c67ed

test:
  secret_key_base: 6272901cf21dc960701c4b0c9a21f9c4e6476b54355c9fd804b1169a9a2769a43e15da90d8c506801cfc12b5c5a64004934a4e8c1bc84f6386e37cbc5cbb1932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
