# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7c5cb461bf3e0050ebb2c5bb6abc3ed8bef51f20ae1d26cc497b51c14646cb6cc0a2614032eee1bc420fcdbc302a6c6b87be2e3121675cfaf1b3ebfdbbdd4d7
  S3_BUCKET_NAME: rawkingbuck
  AWS_ACCESS_KEY_ID: AKIAI3KTWD5U2OAW3F3A
  AWS_SECRET_ACCESS_KEY: 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
test:
  secret_key_base: 80d8a860f4b6c73d38e6a350cef3d34b04fc6d37de6d7a85ecc04062f2972ca672048b38c78272f69268c6d44657bba5bba4aff6bcda706af30ba18ea8a659a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
