# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5f1956ccf54892ab8fd9011d0b99cb92695ec32756a84bba4892c69e6359ad5d24c4e9978bf8f1f753fd86124828f13b31432e48ed2fcdefc0c8849cf35801

test:
  secret_key_base: 30fde5494d15a63dceca04222d0c0e973fea519d1e78619e7ce665ea9033163aaea42fd789563bb900ee5ff3dc227e08501ae8b9751555659e325cc168436ca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
